# Generated by Django 5.1.8 on 2025-04-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tag', models.CharField(max_length=10, unique=True)),
                ('icon', models.ImageField(upload_to='games/')),
                ('retired', models.BooleanField(default=False)),
                ('opsec', models.BooleanField(default=False)),
                ('opsec_user_group', models.IntegerField(blank=True, default=None, null=True)),
                ('opsec_discord_role', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
