services:
  docs:
    image: opserv_local_docs
    container_name: opserv_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./opserv:/app/opserv:z
    ports:
      - '9000:9000'
    command: /start-docs
