# Generated by Django 5.2.3 on 2025-06-13 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billets', '0001_initial'),
        ('games', '0001_initial'),
        ('ranks', '0002_create_default_rank'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='billet',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billets', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='billet',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billets_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='billet',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billets', to='games.game'),
        ),
        migrations.AlterField(
            model_name='billet',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billets', to='billets.billetoffice'),
        ),
        migrations.AlterField(
            model_name='billet',
            name='rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billets', to='ranks.rank'),
        ),
        migrations.AlterField(
            model_name='billet',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billets_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
    ]
