# Generated by Django 5.1.8 on 2025-04-06 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tag', models.CharField(max_length=10)),
                ('color_hex', models.CharField(max_length=7)),
                ('live_fire', models.BooleanField(default=False)),
                ('retired', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('aar_notes', models.TextField(blank=True, null=True)),
                ('is_opsec', models.BooleanField(default=False)),
                ('discord_voice_channel', models.CharField(blank=True, max_length=255, null=True)),
                ('discord_event_location', models.CharField(blank=True, max_length=255, null=True)),
                ('leader_user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operation_leader', to=settings.AUTH_USER_MODEL)),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.operationtype')),
            ],
        ),
    ]
