# Generated by Django 5.1.8 on 2025-04-06 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='game_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='games.game'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operation',
            name='aar_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='discord_event_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='operation',
            name='discord_voice_channel',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
