"""empty message

Revision ID: 15df653d26a8
Revises: 6a7b24f29bd2
Create Date: 2024-11-02 19:36:12.524247

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = "15df653d26a8"
down_revision = "6a7b24f29bd2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activation_code",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=128), nullable=False),
        sa.Column("expired", sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_user_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sqlalchemy_utils.types.arrow.ArrowType(), nullable=False
        ),
        sa.Column("edited_user_id", sa.Integer(), nullable=True),
        sa.Column(
            "edited_at", sqlalchemy_utils.types.arrow.ArrowType(), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["created_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["edited_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="cascade"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "user_audit_log",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("action", sa.String(length=255), nullable=False),
        sa.Column("message", mysql.LONGTEXT(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_user_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sqlalchemy_utils.types.arrow.ArrowType(), nullable=False
        ),
        sa.Column("edited_user_id", sa.Integer(), nullable=True),
        sa.Column(
            "edited_at", sqlalchemy_utils.types.arrow.ArrowType(), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["created_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["edited_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user_audit_log", schema=None) as batch_op:
        batch_op.create_index(
            "ix_user_audit_log_created_at", ["created_at"], unique=False
        )
        batch_op.create_index("ix_user_audit_log_user_id", ["user_id"], unique=False)
        batch_op.create_index("ix_user_audit_log_username", ["username"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_audit_log", schema=None) as batch_op:
        batch_op.drop_index("ix_user_audit_log_username")
        batch_op.drop_index("ix_user_audit_log_user_id")
        batch_op.drop_index("ix_user_audit_log_created_at")

    op.drop_table("user_audit_log")
    op.drop_table("activation_code")
    # ### end Alembic commands ###
