"""empty message

Revision ID: 0f7ba4971220
Revises: 15df653d26a8
Create Date: 2024-11-02 20:23:09.624160

"""

from alembic import op


# revision identifiers, used by Alembic.
revision = "0f7ba4971220"
down_revision = "15df653d26a8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["username"])
        batch_op.create_unique_constraint(None, ["email"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_constraint(None, type_="unique")

    # ### end Alembic commands ###
