"""empty message

Revision ID: 482c23583e52
Revises: 0f7ba4971220
Create Date: 2024-11-03 19:27:27.855801

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "482c23583e52"
down_revision = "0f7ba4971220"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reset_password_code",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=128), nullable=False),
        sa.Column("expired", sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_user_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sqlalchemy_utils.types.arrow.ArrowType(), nullable=False
        ),
        sa.Column("edited_user_id", sa.Integer(), nullable=True),
        sa.Column(
            "edited_at", sqlalchemy_utils.types.arrow.ArrowType(), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["created_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["edited_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="cascade"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reset_password_code")
    # ### end Alembic commands ###
