"""empty message

Revision ID: 07d83c307c61
Revises: 7fdd42b0bd24
Create Date: 2024-11-13 22:14:38.727871

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "07d83c307c61"
down_revision = "7fdd42b0bd24"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recruit_applications", schema=None) as batch_op:
        batch_op.add_column(sa.Column("primary_game_id", sa.Integer(), nullable=False))
        batch_op.add_column(
            sa.Column("referred_by", sa.String(length=255), nullable=True)
        )
        batch_op.add_column(sa.Column("country", sa.String(length=255), nullable=False))
        batch_op.add_column(
            sa.Column("previous_guilds", mysql.LONGTEXT(), nullable=True)
        )
        batch_op.add_column(sa.Column("why_join", mysql.LONGTEXT(), nullable=False))
        batch_op.add_column(sa.Column("experience", mysql.LONGTEXT(), nullable=True))
        batch_op.add_column(sa.Column("other_info", mysql.LONGTEXT(), nullable=True))
        batch_op.add_column(
            sa.Column("primary_id", sa.String(length=255), nullable=True)
        )
        batch_op.add_column(sa.Column("steam_id", sa.String(length=255), nullable=True))
        batch_op.add_column(
            sa.Column("discord_id", sa.String(length=255), nullable=True)
        )
        batch_op.add_column(
            sa.Column("rsi_handle", sa.String(length=255), nullable=True)
        )
        batch_op.create_unique_constraint(None, ["discord_id"])
        batch_op.create_unique_constraint(None, ["rsi_handle"])
        batch_op.create_unique_constraint(None, ["steam_id"])
        batch_op.create_foreign_key(None, "games", ["primary_game_id"], ["id"])
        batch_op.drop_column("submitted_form")

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("referred_by", sa.String(length=255), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("referred_by")

    with op.batch_alter_table("enlistment_applications", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("submitted_form", mysql.LONGTEXT(), nullable=False)
        )
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_column("rsi_handle")
        batch_op.drop_column("discord_id")
        batch_op.drop_column("steam_id")
        batch_op.drop_column("primary_id")
        batch_op.drop_column("other_info")
        batch_op.drop_column("experience")
        batch_op.drop_column("why_join")
        batch_op.drop_column("previous_guilds")
        batch_op.drop_column("country")
        batch_op.drop_column("referred_by")
        batch_op.drop_column("primary_game_id")

    # ### end Alembic commands ###
