"""empty message

Revision ID: 38ac70ff6f16
Revises: b91c0b13e8c2
Create Date: 2024-07-14 02:24:59.020198

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38ac70ff6f16'
down_revision = 'b91c0b13e8c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ranks',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('forum_icon', sa.String(length=255), nullable=False),
    sa.Column('fs_icon', sa.String(length=255), nullable=False),
    sa.Column('color_hex', sa.String(length=7), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.Column('edited_user_id', sa.Integer(), nullable=True),
    sa.Column('edited_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.ForeignKeyConstraint(['created_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['edited_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('billets',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('office_id', sa.Integer(), nullable=True),
    sa.Column('taskforce_id', sa.Integer(), nullable=True),
    sa.Column('rank_id', sa.Integer(), nullable=False),
    sa.Column('last_filled_date', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
    sa.Column('retired', sa.SmallInteger(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.Column('edited_user_id', sa.Integer(), nullable=True),
    sa.Column('edited_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.ForeignKeyConstraint(['created_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['edited_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['rank_id'], ['ranks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('billets')
    op.drop_table('ranks')
    # ### end Alembic commands ###
