"""empty message

Revision ID: b91c0b13e8c2
Revises: 6355730115bc
Create Date: 2024-07-10 12:35:48.459253

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'b91c0b13e8c2'
down_revision = '6355730115bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tag', sa.String(length=10), nullable=False),
    sa.Column('icon', sa.String(length=255), nullable=False),
    sa.Column('retired', sa.Integer(), nullable=False),
    sa.Column('opsec', sa.Integer(), nullable=False),
    sa.Column('opsec_user_group', sa.Integer(), nullable=True),
    sa.Column('opsec_discord_role', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.Column('edited_user_id', sa.Integer(), nullable=True),
    sa.Column('edited_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.ForeignKeyConstraint(['created_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['edited_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operation_types',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tag', sa.String(length=10), nullable=False),
    sa.Column('color_hex', sa.String(length=7), nullable=False),
    sa.Column('live_fire', sa.Integer(), nullable=False),
    sa.Column('retired', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.Column('edited_user_id', sa.Integer(), nullable=True),
    sa.Column('edited_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.ForeignKeyConstraint(['created_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['edited_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_completed', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('date_start', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.Column('date_end', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.Column('leader_user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('aar_notes', sa.Text(), nullable=True),
    sa.Column('is_opsec', sa.Integer(), nullable=False),
    sa.Column('discord_voice_channel', sa.String(length=255), nullable=True),
    sa.Column('discord_event_location', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.Column('edited_user_id', sa.Integer(), nullable=True),
    sa.Column('edited_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.ForeignKeyConstraint(['created_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['edited_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['leader_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['operation_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operations')
    op.drop_table('operation_types')
    op.drop_table('games')
    # ### end Alembic commands ###
