"""empty message

Revision ID: b7a1f4e8d3b1
Revises: f29253c9ae33
Create Date: 2024-08-01 00:51:41.679147

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b7a1f4e8d3b1'
down_revision = 'f29253c9ae33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billets', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=mysql.TEXT(),
               type_=mysql.LONGTEXT(),
               existing_nullable=False)

    with op.batch_alter_table('operations', schema=None) as batch_op:
        batch_op.alter_column('aar_notes',
               existing_type=mysql.TEXT(),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)

    with op.batch_alter_table('ranks', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=mysql.TEXT(),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ranks', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=mysql.LONGTEXT(),
               type_=mysql.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('operations', schema=None) as batch_op:
        batch_op.alter_column('aar_notes',
               existing_type=mysql.LONGTEXT(),
               type_=mysql.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('billets', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=mysql.LONGTEXT(),
               type_=mysql.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
