"""empty message

Revision ID: 1f07b1247550
Revises: b7a1f4e8d3b1
Create Date: 2024-09-01 20:26:18.636941

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1f07b1247550'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('username', mysql.VARCHAR(length=255), nullable=False),
                    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
                    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
                    sa.Column('created_user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
                    sa.Column('created_at', mysql.DATETIME(), nullable=False),
                    sa.Column('edited_user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.Column('edited_at', mysql.DATETIME(), nullable=False),
                    sa.Column('rank_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
                    sa.Column('timezone', mysql.VARCHAR(length=255), nullable=False),
                    sa.ForeignKeyConstraint(['created_user_id'], ['users.id'], name='users_ibfk_1'),
                    sa.ForeignKeyConstraint(['edited_user_id'], ['users.id'], name='users_ibfk_2'),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_collate='utf8mb4_general_ci',
                    mysql_default_charset='utf8mb4',
                    mysql_engine='InnoDB'
                    )
    op.create_table('operation_types',
                    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
                    sa.Column('tag', mysql.VARCHAR(length=10), nullable=False),
                    sa.Column('color_hex', mysql.VARCHAR(length=7), nullable=False),
                    sa.Column('live_fire', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
                    sa.Column('retired', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
                    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
                    sa.Column('created_user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
                    sa.Column('created_at', mysql.DATETIME(), nullable=False),
                    sa.Column('edited_user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.Column('edited_at', mysql.DATETIME(), nullable=False),
                    sa.ForeignKeyConstraint(['created_user_id'], ['users.id'], name='operation_types_ibfk_1'),
                    sa.ForeignKeyConstraint(['edited_user_id'], ['users.id'], name='operation_types_ibfk_2'),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_collate='utf8mb4_general_ci',
                    mysql_default_charset='utf8mb4',
                    mysql_engine='InnoDB'
                    )
    op.create_table('games',
                    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
                    sa.Column('tag', mysql.VARCHAR(length=10), nullable=False),
                    sa.Column('icon', mysql.VARCHAR(length=255), nullable=False),
                    sa.Column('retired', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
                    sa.Column('opsec', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
                    sa.Column('opsec_user_group', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.Column('opsec_discord_role', mysql.VARCHAR(length=255), nullable=True),
                    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
                    sa.Column('created_user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
                    sa.Column('created_at', mysql.DATETIME(), nullable=False),
                    sa.Column('edited_user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.Column('edited_at', mysql.DATETIME(), nullable=False),
                    sa.ForeignKeyConstraint(['created_user_id'], ['users.id'], name='games_ibfk_1'),
                    sa.ForeignKeyConstraint(['edited_user_id'], ['users.id'], name='games_ibfk_2'),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_collate='utf8mb4_general_ci',
                    mysql_default_charset='utf8mb4',
                    mysql_engine='InnoDB'
                    )
    op.create_table('ranks',
                    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
                    sa.Column('description', mysql.LONGTEXT(), nullable=True),
                    sa.Column('forum_icon', mysql.VARCHAR(length=255), nullable=False),
                    sa.Column('fs_icon', mysql.VARCHAR(length=255), nullable=False),
                    sa.Column('color_hex', mysql.VARCHAR(length=7), nullable=False),
                    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
                    sa.Column('created_user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
                    sa.Column('created_at', mysql.DATETIME(), nullable=False),
                    sa.Column('edited_user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.Column('edited_at', mysql.DATETIME(), nullable=False),
                    sa.ForeignKeyConstraint(['created_user_id'], ['users.id'], name='ranks_ibfk_1'),
                    sa.ForeignKeyConstraint(['edited_user_id'], ['users.id'], name='ranks_ibfk_2'),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_collate='utf8mb4_general_ci',
                    mysql_default_charset='utf8mb4',
                    mysql_engine='InnoDB'
                    )

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'ranks', ['rank_id'], ['id'])

    op.create_table('billets',
                    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
                    sa.Column('game_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
                    sa.Column('description', mysql.LONGTEXT(), nullable=False),
                    sa.Column('office_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.Column('taskforce_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.Column('rank_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
                    sa.Column('last_filled_date', mysql.DATETIME(), nullable=True),
                    sa.Column('retired', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False),
                    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
                    sa.Column('created_user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
                    sa.Column('created_at', mysql.DATETIME(), nullable=False),
                    sa.Column('edited_user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.Column('edited_at', mysql.DATETIME(), nullable=False),
                    sa.ForeignKeyConstraint(['created_user_id'], ['users.id'], name='billets_ibfk_1'),
                    sa.ForeignKeyConstraint(['edited_user_id'], ['users.id'], name='billets_ibfk_2'),
                    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name='billets_ibfk_3'),
                    sa.ForeignKeyConstraint(['rank_id'], ['ranks.id'], name='billets_ibfk_4'),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_collate='utf8mb4_general_ci',
                    mysql_default_charset='utf8mb4',
                    mysql_engine='InnoDB'
                    )
    op.create_table('operations',
                    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
                    sa.Column('description', mysql.LONGTEXT(), nullable=True),
                    sa.Column('is_completed', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
                    sa.Column('type_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
                    sa.Column('date_start', mysql.DATETIME(), nullable=False),
                    sa.Column('date_end', mysql.DATETIME(), nullable=False),
                    sa.Column('leader_user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
                    sa.Column('game_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
                    sa.Column('aar_notes', mysql.LONGTEXT(), nullable=True),
                    sa.Column('is_opsec', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
                    sa.Column('discord_voice_channel', mysql.VARCHAR(length=255), nullable=True),
                    sa.Column('discord_event_location', mysql.VARCHAR(length=255), nullable=True),
                    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
                    sa.Column('created_user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
                    sa.Column('created_at', mysql.DATETIME(), nullable=False),
                    sa.Column('edited_user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.Column('edited_at', mysql.DATETIME(), nullable=False),
                    sa.ForeignKeyConstraint(['created_user_id'], ['users.id'], name='operations_ibfk_1'),
                    sa.ForeignKeyConstraint(['edited_user_id'], ['users.id'], name='operations_ibfk_2'),
                    sa.ForeignKeyConstraint(['leader_user_id'], ['users.id'], name='operations_ibfk_4'),
                    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name='operations_ibfk_3'),
                    sa.ForeignKeyConstraint(['type_id'], ['operation_types.id'], name='operations_ibfk_5'),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_collate='utf8mb4_general_ci',
                    mysql_default_charset='utf8mb4',
                    mysql_engine='InnoDB'
                    )
    op.create_table('member_games',
                    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
                    sa.Column('game_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
                    sa.Column('is_primary', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
                    sa.Column('sort_order', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False),
                    sa.Column('created_user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
                    sa.Column('created_at', mysql.DATETIME(), nullable=False),
                    sa.Column('edited_user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.Column('edited_at', mysql.DATETIME(), nullable=False),
                    sa.ForeignKeyConstraint(['created_user_id'], ['users.id'], name='member_games_ibfk_1'),
                    sa.ForeignKeyConstraint(['edited_user_id'], ['users.id'], name='member_games_ibfk_2'),
                    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name='member_games_ibfk_3'),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='member_games_ibfk_4'),
                    sa.PrimaryKeyConstraint('user_id', 'game_id'),
                    mysql_collate='utf8mb4_general_ci',
                    mysql_default_charset='utf8mb4',
                    mysql_engine='InnoDB'
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('member_games')
    op.drop_table('operations')
    op.drop_table('billets')
    op.drop_table('ranks')
    op.drop_table('games')
    op.drop_table('operation_types')
    # ### end Alembic commands ###
