# Generated by Django 5.2.1 on 2025-06-11 18:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.ImageField(upload_to='ranks/icon/')),
                ('fs_icon', models.ImageField(upload_to='ranks/fs/')),
                ('color_hex', models.CharField(default='#FFFFFF', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('users', models.ManyToManyField(blank=True, help_text='Users who have this rank.', related_name='ranks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rank',
                'verbose_name_plural': 'Ranks',
                'ordering': ['order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'is_active'), name='unique_active_rank_name')],
            },
        ),
    ]
