# Generated by Django 5.2.1 on 2025-06-11 19:23

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='description',
            field=tinymce.models.HTMLField(blank=True, help_text='A detailed description of the rank.', null=True),
        ),
    ]
