# Generated by Django 5.2.1 on 2025-06-11 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranks', '0002_alter_rank_description'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='user_set', to='ranks.rank', verbose_name='Rank'),
        ),
    ]
