# Generated by Django 5.2.3 on 2025-06-13 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billets', '0002_billet_user_alter_billet_created_by_and_more'),
        ('users', '0002_user_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='billet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_set', to='billets.billet', verbose_name='Billet'),
        ),
    ]
